import { Marcellus, Source_Sans_3 } from 'next/font/google'
import React from 'react'

/**
 * The two site faces, loaded into the admin panel.
 *
 * The panel's root layout under `(payload)/` is generated by Payload and
 * carries a "do not modify" banner, so there is no element there to hang a
 * `next/font` class on. Instead this provider — which Payload renders inside
 * every admin route, the login screen included — emits one rule that points
 * the parish font tokens at the hashed families `next/font` produced.
 *
 * `custom.scss` declares the same two tokens with plain web-safe fallbacks, so
 * if this ever fails to render the panel degrades to Times/system-sans rather
 * than losing `font-family` altogether. This `<style>` is unlayered and comes
 * later in the document than the stylesheet, so it wins.
 */
const marcellus = Marcellus({
  weight: '400',
  subsets: ['latin', 'latin-ext'],
  display: 'swap',
})

const sourceSans = Source_Sans_3({
  subsets: ['latin', 'latin-ext'],
  display: 'swap',
})

export const Fonts: React.FC<{ children?: React.ReactNode }> = ({ children }) => (
  <>
    <style
      dangerouslySetInnerHTML={{
        __html: `:root{--font-parish-display:${marcellus.style.fontFamily},'Times New Roman',serif;--font-parish-sans:${sourceSans.style.fontFamily},ui-sans-serif,system-ui,sans-serif}`,
      }}
    />
    {children}
  </>
)

export default Fonts
